name: advent2021
version: 0.1.0.0
github: "ijcd/advent2021"
license: BSD3
author: "Ian Duggan"
maintainer: "ijcd@ijcd.com"
copyright: "2021 Ian Duggan"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ijcd/advent2021#readme>

default-extensions:
  - OverloadedStrings
  - RecordWildCards
  # - QuasiQuotes
  # - GeneralizedNewtypeDeriving
  # - ConstraintKinds
  # - FlexibleContexts
  # - TemplateHaskell
  # - FlexibleInstances
  # - NoImplicitPrelude
  # - ScopedTypeVariables

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    # - -Wall
    # - -Werror
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

executables:
  advent2021-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - advent2021

tests:
  advent2021-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - advent2021
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - tasty-smallcheck
